# Generated by Django 5.1.5 on 2025-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lmsrmarket",
            name="outcomes",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="lmsrmarket",
            name="q",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="outcome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="shares",
            field=models.IntegerField(),
        ),
    ]
